<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>StreamDeckk</AssemblyName>
    <RootNamespace>StreamDeckk</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>

    <!-- Tek dosyalık, kurulum gerektirmeyen exe (.NET dahil) -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SatelliteResourceLanguages>tr</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StreamDeckk.Core\StreamDeckk.Core.csproj" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>
</Project>
